version: '3'

services:

    server:
        container_name: mongection_app_17
        image: 10.14.0.97:5500/mongection/app:user17-1.0.1
        environment:
            DBUSER: mongection
            DBPASS: mongection
        ports:
            - "10017:10001"
        labels:
            - "app=mongection"
        networks:
            - a1net
        depends_on:
            - mongo
        external_links:
            - mongo:mongo
        restart: always

    mongo:
        container_name: mongection_db_17
        image: 10.14.0.97:5500/mongection/db-mongo:user17-1.0.1
        ports:
            - "27027:27027"
        labels:
            - "app=mongection"
        volumes:
            - "/var/mongection/data/db_user17:/data/db"
        networks:
            - a1net

networks:
    a1net:
