version: '3'

services:

    server:
        container_name: mongection_app_10
        image: 10.14.0.97:5500/mongection/app:user10-v1.0.0
        environment:
            DBUSER: mongection
            DBPASS: mongection
        ports:
            - "10010:10001"
        labels:
            - "app=mongection"
        networks:
            - a1net
        depends_on:
            - mongo
        external_links:
            - mongo:mongo
        restart: always

    mongo:
        container_name: mongection_db_10
        image: 10.14.0.97:5500/mongection/db-mongo:user10-v1.0.0
        ports:
            - "27010:27017"
        labels:
            - "app=mongection"
        volumes:
            - "/var/mongection/data/db_user10:/data/db"
        networks:
            - a1net

networks:
    a1net:
