kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongection-app
  namespace: mongection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongection-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongection-app
    spec:
      containers:
        - name: container
          image: 'docker.io/prospica/mongection:alpha-v1.0.0'
          ports:
            - containerPort: 10001
              protocol: TCP
          env:
            - name: DBUSER
              value: mongection
            - name: DBPASS
              value: mongection
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
