kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongection-db
  namespace: mongection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongection-db
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongection-db
    spec:
      containers:
        - name: mongection-db
          image: 'docker.io/prospica/monggo-db:alpha-v1.0.0'
          ports:
            - containerPort: 27017
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
